server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/department
    username: root
    password: pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: department-service
  zipkin:
    enabled: true
    service.name: department-service
    sender.type: web
    base-url: http://127.0.0.1:9411/
  sleuth:
    enabled: true
    sampler:
      probability: 1.0

